### ISSUE TITLE
Screen Going Larger

### ISSUE THREAD

**Issue by MattDaoud225** [Swartdogs/PowerScout#52]
There has been errors with the data entry screen sometimes displaying weirdly with all buttons and labels appearing bigger pushing part of the screen to the bottom. unable to recreate this myself, one scout has done it twice at this point. The constraints should be examined.

**Comment by Pr1sM** [comment]
This seems to be related to #49 and #37...

As a possible test @MattDaoud225, can you check to make sure the data entry screen does not have this effect when the UIPickerViews are not open? Is the only trigger of this enlarged state due to the picker view being shown? 

Let me know if you can get the enlarged control state to appear WITHOUT interacting with the picker views. This might be a side effect of those issues.

**Comment by Pr1sM** [comment]
After testing this out in #59 I was not able to get the view hierarchy to change and get big controls. I think this was a side effect of having the old picker view control. I'm closing this for now, but if the same problem appears again, we can reopen this or create a new issue.
