### ISSUE TITLE
Yes/No Consider as Partner

### ISSUE THREAD

**Issue by MattDaoud225** [Swartdogs/PowerScout#80]
We would like to implement a yes/no toggle on whether we should consider them as a partner.

**Comment by MattDaoud225** [comment]
UI elements are implemented in data entry and results view needs to be wired to show on results page however and in export file.

**Comment by Pr1sM** [comment]
@MattDaoud225 In order to do this, you will have to modify the `PowerMatch` class and add a variable that will store this value. There are a couple of ways to do this, but the easiest will be to add a new `Bool` that will represent whether or not the robot is recommended as a partner. Since we are after a 1.0.0 release, we must think about the possibility of an outdated match archive being loaded onto the App and make sure our new variable will get defaulted to `false` if it doesn't exist in the archive.  The following steps are what I recommend for doing this

1. Add the new variable [here](https://github.com/Swartdogs/PowerScout/blob/DylansBranch/PowerScout/Models/PowerMatch.swift#L28). You will have to add a line after this that represents the scouters suggestion. I'm considering this an end game item since we are recommending whether or not to partner with them after we see their performance. Your code will probably look something like this:
```diff
    // End Game Info
    var endClimbCondition:PowerEndClimbPositionType = .none
+   var endRecommendedPartner:Bool = false
```
2. Initialize the variable correctly when a match is loaded from the archive [here](https://github.com/Swartdogs/PowerScout/blob/DylansBranch/PowerScout/Models/PowerMatch.swift#L38-L59). At the end of the function, you will have to add a line that uses the `json` variable to get a value. The only difference is that this might be null with outdated archives, so you will have to add a default value in order to prevent a crash. The code will look something like this:
```diff
        // End Game Info
        endClimbCondition = PowerEndClimbPositionType(rawValue: json["endg"]["climbCond"].intValue)!
+       endRecommendedPartner = json["endg"]["recommend"].bool ?? false
    }
```
3. Update the `messageDictionary` with our new variable. This collection is how the `PowerMatch` instance gets archived between app runs and how it gets packaged when sending data over bluetooth. This is located [here](https://github.com/Swartdogs/PowerScout/blob/DylansBranch/PowerScout/Models/PowerMatch.swift#L61-L89). You will have to add the new variable to the `endg` dictionary with the **same key you used in the previous step**. 
```diff
        // End Game Info
        endg["climbCond"] = endClimbCondition.rawValue as AnyObject?
+       endg["recommend"] = endRecommendedPartner as AnyObject?

        data["auto"] = auto as AnyObject?
        data["tele"] = tele as AnyObject?
        data["endg"] = endg as AnyObject?
        
        return data
    }
```
4. Update the `csvHeader` to add a new column for this value [here](https://github.com/Swartdogs/PowerScout/blob/DylansBranch/PowerScout/Models/PowerMatch.swift#L91-L109). We must think about previous formats of the csv file when finding the correct location for this new column. Since we want to maintain backwards compatibility with previous csv files, the best place for this column is at the _end_ of the list. This will ensure we don't disrupt the previous data in any way -- previous csv files will just not have an entry for this column. Your change will look something like this:
```diff
        // End Game Info
        matchHeader += "End Game Climb Condition, "
        
        // Final Info
-       matchHeader += "Received Tech Fouls, End Robot State \r\n"
+       matchHeader += "Received Tech Fouls, End Robot State, "
+
+       // Additional Info
+       matchHeader += "Recommended as Partner \r\n"

        return matchHeader
    }
```
5. Update the `csvMatch` to add the value of new variable to each `PowerMatch` entry [here](https://github.com/Swartdogs/PowerScout/blob/DylansBranch/PowerScout/Models/PowerMatch.swift#L111-L142). Since our column was added to the end of the list, we must add each instance's data to the end as well:
```diff
        // End Game Info
        matchData += "\(PowerEndClimbPositionType(rawValue: match["endg", "climbCond"].intValue)?.toString() ?? "Unknown"), "
        
        // Final Info
        matchData += "\(match["final", "tFouls"].intValue == 1 ? "Yes" : "No"),"
        matchData += "\(RobotState(rawValue: match["final", "robot"].intValue).toString()),"
+
+       // Additional Info
+       matchData += "\(match["endg","recommend"].bool ?? "N/A"),"

        return matchData
    }
```
